#ifndef SIMPLERSADIGEST_GMP_HELPER_H
#define SIMPLERSADIGEST_GMP_HELPER_H

#define PRIMALITY_TEST_ACCURACY                 (5)

enum {
        NUM_COMPOSITE = 0,
        NUM_PRIME,
};

#endif //SIMPLERSADIGEST_GMP_HELPER_H
